# Cálculo Numérico — Lista de Exercícios: Sistemas Lineares

**Aluno:** Felipe Pinto Zanata — UNIFESP

Este notebook resolve a lista **e** funciona como material de estudo. Cada exercício tem:

- 📘 **Teoria** — o conceito de Cálculo Numérico por trás;
- ✍️ **Resolução manual** — os passos que você faria no papel;
- 🐍 **Python** — o código comentado, com dicas da linguagem;
- 💬 **Interpretação** — o que o resultado significa.

In [1]:
# 🐍 'import ... as ...' carrega uma biblioteca e dá um apelido curto a ela.
# NumPy é a biblioteca padrão de álgebra linear/arrays em Python.
import numpy as np

# Formatação de impressão: 4 casas decimais e sem notação científica para números "normais".
np.set_printoptions(precision=4, suppress=True)

---
## Parte 1 — Conceitos e resolução manual

### Exercício 1 — Sistemas na forma matricial $Ax = b$

📘 **Teoria.** Todo sistema linear pode ser escrito como um produto matriz × vetor:

- $A$ = **matriz dos coeficientes** (linha $i$ = equação $i$, coluna $j$ = coeficiente da incógnita $j$);
- $x$ = **vetor de incógnitas**;
- $b$ = **vetor independente** (os termos do lado direito).

Atenção: incógnita ausente numa equação tem coeficiente **0**, e o sinal faz parte do coeficiente ($x - 3y$ → coeficiente $-3$).

**a)** $\begin{cases}2x + y = 7\\ x - 3y = -5\end{cases}
\;\Longrightarrow\;
\underbrace{\begin{bmatrix}2 & 1\\ 1 & -3\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\ y\end{bmatrix}}_{x}
=
\underbrace{\begin{bmatrix}7\\ -5\end{bmatrix}}_{b}$

**b)** $\begin{cases}x + 2y - z = 2\\ 3x - y + 2z = 9\\ 2x + y + z = 7\end{cases}
\;\Longrightarrow\;
\underbrace{\begin{bmatrix}1 & 2 & -1\\ 3 & -1 & 2\\ 2 & 1 & 1\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\ y\\ z\end{bmatrix}}_{x}
=
\underbrace{\begin{bmatrix}2\\ 9\\ 7\end{bmatrix}}_{b}$

**Verificação:** multiplicando a 1ª linha de $A$ por $x$ no item b: $1\cdot x + 2\cdot y + (-1)\cdot z = 2$ ✔ — é exatamente a 1ª equação.

In [2]:
# 🐍 np.array cria um array a partir de listas. Uma lista de listas vira uma MATRIZ:
#    cada lista interna é uma LINHA. 'dtype=float' evita contas inteiras truncadas.
A1a = np.array([[2,  1],
                [1, -3]], dtype=float)
b1a = np.array([7, -5], dtype=float)

A1b = np.array([[1,  2, -1],
                [3, -1,  2],
                [2,  1,  1]], dtype=float)
b1b = np.array([2, 9, 7], dtype=float)

# 🐍 .shape devolve as dimensões (linhas, colunas) — útil para conferir se montou certo.
print("Item a) A =\n", A1a, "\n   b =", b1a, "  shape de A:", A1a.shape)
print("\nItem b) A =\n", A1b, "\n   b =", b1b, "  shape de A:", A1b.shape)

# Bônus: a solução de cada sistema (o exercício só pede a forma matricial)
print("\nSolução a):", np.linalg.solve(A1a, b1a))
print("Solução b):", np.linalg.solve(A1b, b1b))

Item a) A =
 [[ 2.  1.]
 [ 1. -3.]] 
   b = [ 7. -5.]   shape de A: (2, 2)

Item b) A =
 [[ 1.  2. -1.]
 [ 3. -1.  2.]
 [ 2.  1.  1.]] 
   b = [2. 9. 7.]   shape de A: (3, 3)

Solução a): [2.2857 2.4286]
Solução b): [2. 1. 2.]


💬 **Interpretação.** Escrever na forma $Ax=b$ é o passo que permite ao computador tratar *qualquer* sistema da mesma maneira: o algoritmo só precisa de $A$ e $b$, não das letras $x, y, z$.

### Exercício 2 — Eliminação de Gauss (manual)

📘 **Teoria.** A ideia é transformar o sistema em um **triangular superior** (zeros abaixo da diagonal), usando operações elementares que **não mudam a solução**:

1. trocar duas linhas;
2. multiplicar uma linha por um número $\neq 0$;
3. somar a uma linha um múltiplo de outra: $L_i \leftarrow L_i - m_{ik}\,L_k$.

O número $m_{ik} = \dfrac{a_{ik}}{a_{kk}}$ é o **multiplicador**, e $a_{kk}$ é o **pivô**. Depois, resolvemos de baixo para cima (**substituição regressiva**).

$$\begin{cases}2x + y - z = 8\\ -3x - y + 2z = -11\\ -2x + y + 2z = -3\end{cases}$$

**Matriz aumentada** $[A\,|\,b]$:
$$\left[\begin{array}{rrr|r} 2 & 1 & -1 & 8\\ -3 & -1 & 2 & -11\\ -2 & 1 & 2 & -3 \end{array}\right]$$

**Etapa 1 — zerar a coluna 1 abaixo do pivô $a_{11}=2$**

- $m_{21} = -3/2 = -1{,}5 \Rightarrow L_2 \leftarrow L_2 + 1{,}5\,L_1$
- $m_{31} = -2/2 = -1 \Rightarrow L_3 \leftarrow L_3 + L_1$

$$\left[\begin{array}{rrr|r} 2 & 1 & -1 & 8\\ 0 & 0{,}5 & 0{,}5 & 1\\ 0 & 2 & 1 & 5 \end{array}\right]$$

(conta da $L_2$: $-3+1{,}5\cdot2=0$; $\;-1+1{,}5\cdot1=0{,}5$; $\;2+1{,}5\cdot(-1)=0{,}5$; $\;-11+1{,}5\cdot8=1$)

**Etapa 2 — zerar a coluna 2 abaixo do pivô $a_{22}=0{,}5$**

- $m_{32} = 2/0{,}5 = 4 \Rightarrow L_3 \leftarrow L_3 - 4\,L_2$

$$\left[\begin{array}{rrr|r} 2 & 1 & -1 & 8\\ 0 & 0{,}5 & 0{,}5 & 1\\ 0 & 0 & -1 & 1 \end{array}\right]$$

**Substituição regressiva** (de baixo para cima):

- $-z = 1 \Rightarrow \boxed{z = -1}$
- $0{,}5y + 0{,}5(-1) = 1 \Rightarrow 0{,}5y = 1{,}5 \Rightarrow \boxed{y = 3}$
- $2x + 3 - (-1) = 8 \Rightarrow 2x = 4 \Rightarrow \boxed{x = 2}$

**Verificação** na 3ª equação original: $-2(2) + 3 + 2(-1) = -4+3-2 = -3$ ✔

In [3]:
# Reproduzindo as etapas manuais "na mão" com NumPy, para ver cada matriz.
# 🐍 np.column_stack junta A e b lado a lado → matriz aumentada.
A2 = np.array([[ 2,  1, -1],
               [-3, -1,  2],
               [-2,  1,  2]], dtype=float)
b2 = np.array([8, -11, -3], dtype=float)

M = np.column_stack((A2, b2))
print("Matriz aumentada inicial:\n", M)

# 🐍 Fatiamento: M[1] é a linha 2 (Python conta a partir de 0!).
#    M[1] = M[1] - m*M[0] faz a operação na linha inteira de uma vez (vetorização).
M[1] = M[1] - (M[1, 0] / M[0, 0]) * M[0]   # L2 <- L2 - m21*L1
M[2] = M[2] - (M[2, 0] / M[0, 0]) * M[0]   # L3 <- L3 - m31*L1
print("\nApós etapa 1:\n", M)

M[2] = M[2] - (M[2, 1] / M[1, 1]) * M[1]   # L3 <- L3 - m32*L2
print("\nApós etapa 2 (triangular superior):\n", M)

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Após etapa 1:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Após etapa 2 (triangular superior):
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]


---
## Parte 2 — Propriedades e interpretação

### Exercício 3 — Número de soluções

📘 **Teoria.** Após escalonar $[A\,|\,b]$, olhamos a última linha:

| Situação após a redução | Classificação |
|---|---|
| Todo pivô na diagonal é $\neq 0$ | **Solução única** (sistema possível e determinado — SPD) |
| Aparece linha $[0\;0\,|\,0]$ | **Infinitas soluções** (possível e indeterminado — SPI) |
| Aparece linha $[0\;0\,|\,c]$ com $c\neq0$ | **Nenhuma solução** (impossível — SI), pois diz $0=c$ |

Formalmente (Teorema de Rouché–Capelli): compara-se o **posto** de $A$ com o de $[A|b]$ e com o número de incógnitas $n$.

**a)** $\left[\begin{array}{rr|r}1&1&3\\2&2&6\end{array}\right] \xrightarrow{L_2-2L_1} \left[\begin{array}{rr|r}1&1&3\\0&0&0\end{array}\right]$

A 2ª equação virou $0=0$ (é só o dobro da 1ª). Resta uma equação para duas incógnitas → **infinitas soluções**: $x = 3 - t,\; y = t$, $t\in\mathbb R$. *(Geometricamente: as duas retas são a mesma.)*

**b)** $\left[\begin{array}{rr|r}1&1&3\\2&2&7\end{array}\right] \xrightarrow{L_2-2L_1} \left[\begin{array}{rr|r}1&1&3\\0&0&1\end{array}\right]$

A 2ª linha diz $0x+0y=1$, ou seja $0=1$: absurdo → **nenhuma solução**. *(Retas paralelas distintas.)*

**c)** $\left[\begin{array}{rr|r}1&1&3\\2&-1&0\end{array}\right] \xrightarrow{L_2-2L_1} \left[\begin{array}{rr|r}1&1&3\\0&-3&-6\end{array}\right]$

Dois pivôs não nulos → **solução única**: $y = -6/-3 = 2$, $x = 3-2 = 1$. *(Retas concorrentes no ponto $(1,2)$.)*

In [4]:
# Conferindo pelo posto (rank). 🐍 np.linalg.matrix_rank calcula o posto de uma matriz.
# 🐍 Um dicionário {chave: valor} guarda os três casos; .items() percorre os pares.
casos = {
    "a": (np.array([[1, 1], [2,  2]], float), np.array([3, 6], float)),
    "b": (np.array([[1, 1], [2,  2]], float), np.array([3, 7], float)),
    "c": (np.array([[1, 1], [2, -1]], float), np.array([3, 0], float)),
}

def classificar(A, b):
    # 🐍 'def' define uma função; o que vem após 'return' é o resultado dela.
    n = A.shape[1]                                      # número de incógnitas
    posto_A  = np.linalg.matrix_rank(A)
    posto_Ab = np.linalg.matrix_rank(np.column_stack((A, b)))
    if posto_A != posto_Ab:
        return posto_A, posto_Ab, "nenhuma solução (SI)"
    elif posto_A == n:
        return posto_A, posto_Ab, "solução única (SPD)"
    else:
        return posto_A, posto_Ab, "infinitas soluções (SPI)"

for item, (A, b) in casos.items():
    pA, pAb, tipo = classificar(A, b)       # 🐍 "desempacotamento" de uma tupla em 3 variáveis
    print(f"{item})  posto(A) = {pA}, posto([A|b]) = {pAb}  →  {tipo}")
    # 🐍 f-strings: o que está entre { } é calculado e inserido no texto.

print("\nSolução de c):", np.linalg.solve(*casos["c"]))   # 🐍 '*' espalha a tupla (A, b) como 2 argumentos

a)  posto(A) = 1, posto([A|b]) = 1  →  infinitas soluções (SPI)
b)  posto(A) = 1, posto([A|b]) = 2  →  nenhuma solução (SI)
c)  posto(A) = 2, posto([A|b]) = 2  →  solução única (SPD)

Solução de c): [1. 2.]


💬 **Interpretação.** Nos casos a) e b) a matriz $A$ é **singular** ($\det A = 1\cdot2-1\cdot2 = 0$): as linhas são proporcionais. Quando $\det A=0$, o sistema nunca tem solução única — quem decide entre "infinitas" e "nenhuma" é o vetor $b$. Por isso `np.linalg.solve` daria erro em a) e b).

---
## Parte 3 — Implementação numérica em Python

### Exercício 4 — Eliminação de Gauss sem pivoteamento

📘 **Algoritmo** (para $A$ de ordem $n$):

```
para k = 0 até n-2:                    # coluna do pivô
    para i = k+1 até n-1:              # linhas abaixo do pivô
        m = M[i,k] / M[k,k]            # multiplicador
        L_i ← L_i − m · L_k
para i = n-1 descendo até 0:           # substituição regressiva
    x[i] = ( M[i,n] − Σ_{j>i} M[i,j]·x[j] ) / M[i,i]
```

"Sem pivoteamento" significa que **não trocamos linhas**: se algum pivô $a_{kk}$ der 0, o método falha (divisão por zero), mesmo que o sistema tenha solução. Por isso o código verifica isso e avisa.

**Custo:** a eliminação faz cerca de $\tfrac{2}{3}n^3$ operações; a substituição, $n^2$.

In [5]:
def eliminacao_gauss(A, b, verbose=True, tol=1e-12):
    """
    Resolve Ax = b por eliminação de Gauss SEM pivoteamento.

    Parâmetros
    ----------
    A : matriz n x n (lista de listas ou np.ndarray)
    b : vetor de tamanho n
    verbose : se True, imprime a matriz aumentada a cada etapa
    tol : valores com |pivô| < tol são tratados como zero

    Retorna
    -------
    x : np.ndarray com a solução
    """
    # 🐍 Texto entre aspas triplas logo após o 'def' é a docstring: documentação da função
    #    (aparece ao digitar help(eliminacao_gauss)).

    # 1) Conversão e validação das entradas
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[0]
    if A.shape != (n, n) or b.shape != (n,):
        raise ValueError("A deve ser n x n e b deve ter n elementos.")
        # 🐍 'raise' interrompe a função lançando um erro com mensagem clara.

    # 2) Matriz aumentada [A | b]   (np.column_stack cria uma CÓPIA: A e b originais ficam intactos)
    M = np.column_stack((A, b))
    if verbose:
        print("Matriz aumentada inicial:\n", M, "\n")

    # 3) Eliminação: zera os elementos abaixo de cada pivô
    for k in range(n - 1):                     # 🐍 range(n-1) gera 0, 1, ..., n-2
        pivo = M[k, k]
        if abs(pivo) < tol:
            raise ZeroDivisionError(
                f"Pivô nulo na posição ({k+1},{k+1}). Sem pivoteamento o método não pode continuar."
            )
        for i in range(k + 1, n):
            m = M[i, k] / pivo                 # multiplicador m_ik
            M[i, k:] = M[i, k:] - m * M[k, k:] # 🐍 M[i, k:] = linha i, da coluna k até o fim
            if verbose:
                print(f"  L{i+1} <- L{i+1} - ({m:.4g})·L{k+1}")
        if verbose:
            print(f"Após zerar a coluna {k+1}:\n", M, "\n")

    if abs(M[n - 1, n - 1]) < tol:
        raise ZeroDivisionError("Último pivô nulo: a matriz é singular.")

    # 4) Substituição regressiva: de baixo para cima
    x = np.zeros(n)                            # 🐍 vetor de n zeros para guardar a solução
    for i in range(n - 1, -1, -1):             # 🐍 range(início, fim, passo): n-1, n-2, ..., 0
        soma = M[i, i+1:n] @ x[i+1:n]          # 🐍 '@' é o produto escalar/matricial
        x[i] = (M[i, n] - soma) / M[i, i]

    if verbose:
        print("Solução x =", x)
    return x

🐍 **Por que `M[i, k:]` em vez de um laço sobre as colunas?** Operar na fatia inteira de uma vez é *vetorização*: o NumPy executa o laço em C, muito mais rápido que um `for` em Python puro. Começar em `k` (e não em 0) economiza contas, pois as colunas anteriores já são zero.

#### Teste com o sistema do Exercício 2

In [6]:
x_gauss = eliminacao_gauss(A2, b2)

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]] 

  L2 <- L2 - (-1.5)·L1
  L3 <- L3 - (-1)·L1
Após zerar a coluna 1:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]] 

  L3 <- L3 - (4)·L2
Após zerar a coluna 2:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]] 

Solução x = [ 2.  3. -1.]


In [7]:
# Comparação com a função pronta do NumPy (que usa fatoração LU com pivoteamento parcial, via LAPACK)
x_numpy = np.linalg.solve(A2, b2)

print("Gauss (nosso):   ", x_gauss)
print("numpy.linalg.solve:", x_numpy)
print("Diferença máxima |x_gauss - x_numpy| =", np.max(np.abs(x_gauss - x_numpy)))
print("Resíduo ||A·x - b|| =", np.linalg.norm(A2 @ x_gauss - b2))

# 🐍 np.allclose compara arrays tolerando pequenos erros de arredondamento.
#    NUNCA compare floats com '==' : 0.1 + 0.2 == 0.3 é False em Python!
print("Resultados coincidem?", np.allclose(x_gauss, x_numpy))

Gauss (nosso):    [ 2.  3. -1.]
numpy.linalg.solve: [ 2.  3. -1.]
Diferença máxima |x_gauss - x_numpy| = 1.2212453270876722e-15
Resíduo ||A·x - b|| = 0.0
Resultados coincidem? True


In [8]:
# Mostrando a limitação do "sem pivoteamento": pivô a11 = 0, mas o sistema tem solução (x=1, y=2).
# 🐍 try/except captura o erro em vez de deixar o programa parar.
A_ruim = [[0, 1],
          [1, 1]]
b_ruim = [2, 3]
try:
    eliminacao_gauss(A_ruim, b_ruim, verbose=False)
except ZeroDivisionError as erro:
    print("Falhou:", erro)
print("numpy.linalg.solve (com pivoteamento):", np.linalg.solve(A_ruim, b_ruim))

Falhou: Pivô nulo na posição (1,1). Sem pivoteamento o método não pode continuar.
numpy.linalg.solve (com pivoteamento): [1. 2.]


💬 **Interpretação.** Nossa implementação reproduz $x=2,\;y=3,\;z=-1$, igual ao `numpy.linalg.solve`, com diferença na ordem de $10^{-15}$ ou menor — apenas erro de arredondamento de ponto flutuante. O resíduo $\|Ax-b\|\approx 0$ confirma a solução.

O último teste mostra por que bibliotecas profissionais usam **pivoteamento parcial** (trocar linhas para usar o maior $|a_{ik}|$ como pivô): ele evita pivôs nulos e reduz a amplificação de erros quando o pivô é muito pequeno.

---
## Parte 4 — Aplicação

### Exercício 5 — Balanço térmico

$$\begin{bmatrix}4 & -1 & 0\\ -1 & 4 & -1\\ 0 & -1 & 3\end{bmatrix}
\begin{bmatrix}T_1\\T_2\\T_3\end{bmatrix} = \begin{bmatrix}15\\10\\10\end{bmatrix}$$

📘 **Contexto.** Cada linha é um balanço de energia num nó: a temperatura de um nó depende das vizinhas (os $-1$ são as conexões entre nós). Matrizes assim são **tridiagonais** e **diagonalmente dominantes** ($|a_{ii}| > \sum_{j\neq i}|a_{ij}|$: $4>1$, $4>2$, $3>1$), o que garante que a eliminação de Gauss **sem pivoteamento** funciona bem: nenhum pivô se anula.

#### a) Resolução manual

$$\left[\begin{array}{rrr|r} 4 & -1 & 0 & 15\\ -1 & 4 & -1 & 10\\ 0 & -1 & 3 & 10 \end{array}\right]$$

**Etapa 1:** $m_{21} = -1/4 \Rightarrow L_2 \leftarrow L_2 + \tfrac14 L_1$; $\;m_{31}=0$ (já é zero, nada a fazer).

$L_2$: $\;4 - \tfrac14 = \tfrac{15}{4}$, $\;-1$, $\;10 + \tfrac{15}{4} = \tfrac{55}{4}$

$$\left[\begin{array}{rrr|r} 4 & -1 & 0 & 15\\ 0 & \tfrac{15}{4} & -1 & \tfrac{55}{4}\\ 0 & -1 & 3 & 10 \end{array}\right]$$

**Etapa 2:** $m_{32} = \dfrac{-1}{15/4} = -\tfrac{4}{15} \Rightarrow L_3 \leftarrow L_3 + \tfrac{4}{15} L_2$

$L_3$: $\;3 - \tfrac{4}{15} = \tfrac{41}{15}$, $\quad 10 + \tfrac{4}{15}\cdot\tfrac{55}{4} = 10 + \tfrac{11}{3} = \tfrac{41}{3}$

$$\left[\begin{array}{rrr|r} 4 & -1 & 0 & 15\\ 0 & \tfrac{15}{4} & -1 & \tfrac{55}{4}\\ 0 & 0 & \tfrac{41}{15} & \tfrac{41}{3} \end{array}\right]$$

**Substituição regressiva:**

- $T_3 = \dfrac{41/3}{41/15} = \dfrac{15}{3} = \boxed{5}$
- $\tfrac{15}{4}T_2 - 5 = \tfrac{55}{4} \Rightarrow \tfrac{15}{4}T_2 = \tfrac{75}{4} \Rightarrow \boxed{T_2 = 5}$
- $4T_1 - 5 = 15 \Rightarrow \boxed{T_1 = 5}$

**Verificação:** $4(5)-5 = 15$ ✔; $\;-5+20-5 = 10$ ✔; $\;-5+15 = 10$ ✔

#### b) Implementação em Python

Reaproveitamos a função do Exercício 4 — essa é a vantagem de escrever funções: escreve uma vez, usa em qualquer sistema.

In [9]:
A5 = np.array([[ 4, -1,  0],
               [-1,  4, -1],
               [ 0, -1,  3]], dtype=float)
b5 = np.array([15, 10, 10], dtype=float)

T = eliminacao_gauss(A5, b5)

print("\nConferência com numpy.linalg.solve:", np.linalg.solve(A5, b5))
print("Resíduo ||A·T - b|| =", np.linalg.norm(A5 @ T - b5))

# 🐍 enumerate devolve (índice, valor); start=1 faz a contagem começar em 1.
for i, Ti in enumerate(T, start=1):
    print(f"T{i} = {Ti:.4f}")

Matriz aumentada inicial:
 [[ 4. -1.  0. 15.]
 [-1.  4. -1. 10.]
 [ 0. -1.  3. 10.]] 

  L2 <- L2 - (-0.25)·L1
  L3 <- L3 - (0)·L1
Após zerar a coluna 1:
 [[ 4.   -1.    0.   15.  ]
 [ 0.    3.75 -1.   13.75]
 [ 0.   -1.    3.   10.  ]] 

  L3 <- L3 - (-0.2667)·L2
Após zerar a coluna 2:
 [[ 4.     -1.      0.     15.    ]
 [ 0.      3.75   -1.     13.75  ]
 [ 0.      0.      2.7333 13.6667]] 

Solução x = [5. 5. 5.]

Conferência com numpy.linalg.solve: [5. 5. 5.]
Resíduo ||A·T - b|| = 0.0
T1 = 5.0000
T2 = 5.0000
T3 = 5.0000


In [10]:
# Conferindo a dominância diagonal estrita com uma linha de NumPy:
# 🐍 np.diag pega a diagonal; .sum(axis=1) soma cada linha; o resultado é um array de True/False.
diag = np.abs(np.diag(A5))
fora = np.abs(A5).sum(axis=1) - diag
print("|a_ii|              :", diag)
print("Σ |a_ij| (j ≠ i)    :", fora)
print("Diagonal dominante? ", np.all(diag > fora))

|a_ii|              : [4. 4. 3.]
Σ |a_ij| (j ≠ i)    : [1. 2. 1.]
Diagonal dominante?  True


💬 **Interpretação.** As três temperaturas valem $T_1=T_2=T_3=5$: a rede está em **equilíbrio uniforme** com essas fontes. A solução manual (feita com frações exatas) e a numérica coincidem, e o resíduo nulo confirma o resultado. A dominância diagonal explica por que o método sem pivoteamento foi seguro aqui.

---
## Resumo

| Exercício | Resultado |
|---|---|
| 1a | $A=\begin{bmatrix}2&1\\1&-3\end{bmatrix},\;b=(7,-5)$ |
| 1b | $A=\begin{bmatrix}1&2&-1\\3&-1&2\\2&1&1\end{bmatrix},\;b=(2,9,7)$ |
| 2 | $x=2,\;y=3,\;z=-1$ |
| 3 | a) infinitas · b) nenhuma · c) única $(1,2)$ |
| 4 | Gauss implementado; coincide com `numpy.linalg.solve` |
| 5 | $T_1=T_2=T_3=5$ |